apiVersion: v1
kind: Service
metadata:
  name: youtube-app-service
spec:
  selector:
    app: youtube-app
  type: LoadBalancer   # use NodePort or ClusterIP if you don't have a cloud LB
  ports:
  - protocol: TCP
    port: 80            # external port
    targetPort: 3000    # must match containerPort in Deployment
